/**
 * A static pool of first names for the demo dashboard greeting
 * ("Good news, <name>."). Picked at random per request.
 */
export const NAMES: string[] = [
  "Aaliyah", "Aaron", "Abby", "Abel", "Abigail", "Ada", "Adam", "Adele", "Adrian", "Aditi",
  "Agnes", "Ahmed", "Aiden", "Aisha", "Ajay", "Akira", "Alan", "Alba", "Albert", "Alejandro",
  "Alex", "Alexa", "Alexander", "Alexis", "Alfie", "Alice", "Alicia", "Alina", "Alison", "Allison",
  "Alma", "Amara", "Amber", "Amelia", "Amir", "Amos", "Amy", "Ana", "Anders", "Andre",
  "Andrea", "Andrew", "Angela", "Angelo", "Anika", "Anita", "Anna", "Anne", "Anthony", "Antoine",
  "Antonio", "Anya", "Aran", "Aria", "Ariel", "Arjun", "Arlo", "Armand", "Arnav", "Arthur",
  "Arya", "Asha", "Ashley", "Asma", "Astrid", "Aubrey", "August", "Aurora", "Austin", "Ava",
  "Avery", "Axel", "Ayaan", "Ayla", "Bao", "Barbara", "Beatrice", "Bella", "Ben", "Benjamin",
  "Bernard", "Beth", "Bianca", "Bilal", "Bjorn", "Blake", "Bo", "Bobby", "Bonnie", "Boris",
  "Brandon", "Brenda", "Brian", "Bridget", "Brooke", "Bruno", "Bryan", "Caleb", "Camila", "Cameron",
  "Carl", "Carla", "Carlos", "Carmen", "Carol", "Caroline", "Carter", "Casey", "Cassie", "Catalina",
  "Catherine", "Cecilia", "Cedric", "Celeste", "Cesar", "Chad", "Charles", "Charlie", "Charlotte", "Chen",
  "Chioma", "Chloe", "Chris", "Christian", "Christina", "Cian", "Claire", "Clara", "Claude", "Clement",
  "Cody", "Cole", "Colin", "Connor", "Cora", "Corey", "Cristina", "Cynthia", "Dahlia", "Daisy",
  "Dakota", "Dale", "Damian", "Daniel", "Daniela", "Danny", "Daphne", "Darius", "David", "Dawn",
  "Dean", "Deborah", "Declan", "Delphine", "Denis", "Denise", "Dennis", "Derek", "Diana", "Diego",
  "Dimitri", "Dina", "Dominic", "Donald", "Dora", "Dorian", "Dorothy", "Douglas", "Duncan", "Dylan",
  "Ebony", "Eddie", "Edgar", "Edith", "Eduardo", "Edward", "Edwin", "Eitan", "Elaine", "Eleanor",
  "Elena", "Eli", "Elias", "Elif", "Elijah", "Elise", "Eliza", "Elizabeth", "Ella", "Ellie",
  "Elliot", "Eloise", "Elsa", "Emanuel", "Emil", "Emilia", "Emily", "Emma", "Emmanuel", "Enzo",
  "Eric", "Erica", "Erik", "Erin", "Esther", "Ethan", "Eva", "Evan", "Evelyn", "Ezra",
  "Fabian", "Faith", "Farah", "Farida", "Fatima", "Felix", "Fernanda", "Finn", "Fiona", "Flora",
  "Florence", "Frances", "Francis", "Francesca", "Franco", "Frank", "Freddie", "Freya", "Gabriel", "Gabriela",
  "Gael", "Gareth", "Gary", "Gemma", "George", "Georgia", "Gerald", "Gianna", "Gideon", "Gina",
  "Giulia", "Grace", "Graham", "Grant", "Greta", "Gus", "Gwen", "Hadley", "Hana", "Hannah",
  "Harold", "Harper", "Harriet", "Harry", "Hassan", "Hazel", "Heather", "Hector", "Heidi", "Helen",
  "Helena", "Henry", "Hina", "Holly", "Hugo", "Hunter", "Ian", "Ibrahim", "Ida", "Idris",
  "Ilya", "Imani", "Imran", "Ines", "Ingrid", "Irene", "Iris", "Isaac", "Isabel", "Isabella",
  "Isla", "Ismael", "Ivan", "Ivy", "Jack", "Jackson", "Jacob", "Jade", "Jake", "James",
  "Jamie", "Jan", "Jane", "Janet", "Jared", "Jasmine", "Jason", "Javier", "Jay", "Jean",
  "Jeff", "Jenna", "Jennifer", "Jeremy", "Jess", "Jessica", "Jesus", "Jia", "Jill", "Jim",
  "Joan", "Joanna", "Joaquin", "Joe", "Joel", "Johanna", "John", "Jonah", "Jonas", "Jordan",
  "Jorge", "Jose", "Joseph", "Josh", "Joshua", "Joy", "Juan", "Judith", "Jules", "Julia",
  "Julian", "Julie", "Juliet", "June", "Junho", "Justin", "Kai", "Kaitlyn", "Kareem", "Karen",
  "Karim", "Karina", "Karl", "Kate", "Katherine", "Kathy", "Katie", "Kayla", "Keira", "Keith",
  "Kelly", "Ken", "Kenji", "Kevin", "Khalid", "Kiara", "Kim", "Kira", "Klaus", "Kofi",
  "Krishna", "Kristen", "Kyle", "Lara", "Larry", "Laura", "Lauren", "Laurent", "Layla", "Leah",
  "Lena", "Leo", "Leon", "Leona", "Leonardo", "Leslie", "Lewis", "Lia", "Liam", "Lila",
  "Lily", "Lina", "Linda", "Linh", "Lionel", "Lisa", "Liv", "Logan", "Lola", "Lorenzo",
  "Louis", "Louise", "Luca", "Lucas", "Lucia", "Lucy", "Luis", "Luka", "Luke", "Luna",
  "Lydia", "Mabel", "Maddox", "Madison", "Mads", "Mae", "Maeve", "Magnus", "Mahmoud", "Maia",
  "Maja", "Malik", "Mara", "Marco", "Marcus", "Margaret", "Maria", "Mariam", "Marie", "Marina",
  "Mario", "Marion", "Marisol", "Mark", "Marta", "Martha", "Martin", "Mary", "Mason", "Mateo",
  "Mathias", "Matias", "Matt", "Matthew", "Maureen", "Max", "Maxwell", "Maya", "Megan", "Mehmet",
  "Mei", "Melanie", "Melissa", "Mercedes", "Mia", "Micah", "Michael", "Michelle", "Miguel", "Mika",
  "Mikael", "Mila", "Miles", "Millie", "Mina", "Mira", "Miriam", "Mohamed", "Mona", "Monica",
  "Morgan", "Moses", "Muhammad", "Mustafa", "Nadia", "Nancy", "Naomi", "Natalia", "Natasha", "Nathan",
  "Neil", "Nell", "Nelson", "Nia", "Niamh", "Nicholas", "Nicole", "Nikhil", "Niko", "Nina",
  "Noah", "Noel", "Nora", "Norah", "Nour", "Oden", "Olga", "Olive", "Oliver", "Olivia",
  "Omar", "Oona", "Oscar", "Otto", "Owen", "Pablo", "Paige", "Paloma", "Pam", "Paola",
  "Patricia", "Patrick", "Paul", "Paula", "Pedro", "Penelope", "Peter", "Petra", "Philip", "Phoebe",
  "Pierre", "Pippa", "Piper", "Polly", "Priya", "Quentin", "Quinn", "Rachel", "Rafael", "Rahul",
  "Ralph", "Ramon", "Rania", "Raphael", "Raul", "Ravi", "Ray", "Rebecca", "Reese", "Remy",
  "Rena", "Rene", "Reuben", "Rhys", "Ricardo", "Richard", "Rick", "Rita", "Riya", "Robert",
  "Robin", "Rocco", "Roger", "Rohan", "Roman", "Romeo", "Ronald", "Rory", "Rosa", "Rose",
  "Rosie", "Ross", "Roxana", "Ruben", "Ruby", "Rui", "Russell", "Ruth", "Ryan", "Sabrina",
  "Sadie", "Sage", "Said", "Sally", "Salma", "Sam", "Samira", "Samuel", "Sandra", "Santiago",
  "Sara", "Sarah", "Sasha", "Saul", "Scarlett", "Scott", "Sean", "Sebastian", "Selena", "Selin",
  "Serena", "Sergei", "Seth", "Shane", "Shaun", "Shauna", "Sheila", "Shirley", "Sienna", "Silas",
  "Silvia", "Simon", "Simone", "Sina", "Sofia", "Sol", "Solomon", "Sonia", "Sophia", "Sophie",
  "Spencer", "Stanley", "Stella", "Stephanie", "Stephen", "Steven", "Stuart", "Sven", "Sydney", "Tahlia",
  "Talia", "Tam", "Tamar", "Tanya", "Tara", "Tariq", "Tatiana", "Taylor", "Ted", "Teresa",
  "Tess", "Thabo", "Thalia", "Thea", "Theo", "Theodore", "Thomas", "Tia", "Tim", "Tina",
  "Tobias", "Toby", "Tom", "Tomas", "Tony", "Tracy", "Trevor", "Tristan", "Tyler", "Uma",
  "Uri", "Ursula", "Valentina", "Valerie", "Vanessa", "Vera", "Veronica", "Victor", "Victoria", "Vihaan",
  "Vikram", "Vince", "Violet", "Vivian", "Wade", "Walter", "Wanda", "Warren", "Wendy", "Wesley",
  "Wilhelmina", "Will", "William", "Willow", "Wyatt", "Xavier", "Ximena", "Yara", "Yasmin", "Yosef",
  "Yuki", "Yusuf", "Yvonne", "Zachary", "Zahra", "Zaid", "Zane", "Zara", "Zayd", "Zoe",
  "Zoya",
];

/** A random first name from the pool. */
export function randomName(): string {
  return NAMES[Math.floor(Math.random() * NAMES.length)]!;
}
